# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d39f73a9167b9b7792164948025f0791d7d1201f2037a9ab818c34f4b17a7f7b8c62f893af162f24f56c53914e9b92f77a7d9d387aca05037a7f0d84101757c1

test:
  secret_key_base: 710edbb21f21fe3cd40cba17de5b34b601c4b88e3ab01ab5baac3df02c4cd1f1ad64e4cd9859d1b62b3e262509163eceb865e5fb45925ec9f6477e164d4878c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
